In [2]:
print('a' * 5)
print(2025)

aaaaa
2025


变量的赋值

In [3]:
a = 10
print(a * 10)

100


# 一、ndarray
## 1.ndarray的特性
### 多维性

In [3]:
import numpy as np
arr = np.array(5) #0维
print('arr的维度：',arr.ndim)
print(arr)

arr的维度： 0
5


In [5]:
arr1 = np.array([1,2,3,4])
print('arr的维度：',arr1.ndim)
print(arr1)

arr的维度： 1
[1 2 3 4]


In [9]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print('arr的维度：',arr2.ndim)
print(arr2)
print(arr2.shape,arr2.size,arr2.dtype)  #形状，元素，类型
print(arr2.T)  #转置

arr的维度： 2
[[1 2 3 4]
 [5 6 7 8]]
(2, 4) 8 int32
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


## 2.ndarray的创建

In [11]:
list1 = [1,2,3,4]
arr = np.array(list1,dtype=np.float64) #强制类型转换
print(arr)
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3. 4.]
[1. 2. 3. 4.]


### 预定义数组，全0，全1，未初始化

In [18]:
arr = np.zeros((2,4),dtype=int)
print(arr)
print('------------------')
arr = np.ones((5,5),dtype=int)
print(arr)
print('------------------')
arr = np.empty((2,2))
print(arr)
print('------------------')
arr = np.full((3,4),2025)
print(arr)


[[0 0 0 0]
 [0 0 0 0]]
------------------
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
------------------
[[0. 0.]
 [0. 0.]]
------------------
[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


## 3.等差数列

In [28]:
arr = np.arange(2,10,2)  # start,end,step
print(arr)
#等间隔数列
arr = np.linspace(0,10,5)  #分割几份
print(arr)
#对数间隔
arr = np.logspace(0,4,3,dtype=int,base=2)
print(arr)

[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[ 1  4 16]


## 特殊矩阵

In [29]:
arr = np.eye(4,dtype=int)
print(arr)
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
#生成0-1随机
arr = np.random.rand(2,3)
#生成浮点数
arr = np.random.uniform(3,10,(2,3))
#生成随机整数
arr = np.random.randint(1,100,(3,3))

#正太分布
arr = np.random.randn(2,4)

#随机种子
# np.random.seed(0)
arr1 = np.random.randint(1,10,(3,3))
print(arr1)
arr2 = np.random.randint(1,10,(3,3))
print(arr2)
print(arr1 @ arr2)  #矩阵乘法

[[9 5 1]
 [3 6 6]
 [1 9 2]]
[[2 1 4]
 [9 9 5]
 [5 1 4]]
[[68 55 65]
 [90 63 66]
 [93 84 57]]
